/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IExchangeIssuanceZeroEx,
  IExchangeIssuanceZeroExInterface,
} from "../IExchangeIssuanceZeroEx";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_issuanceModule",
        type: "address",
      },
    ],
    name: "approveSetToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_spender",
        type: "address",
      },
    ],
    name: "approveToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20[]",
        name: "_tokens",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "_spender",
        type: "address",
      },
    ],
    name: "approveTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_issuanceModule",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_isDebtIssuance",
        type: "bool",
      },
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountSetToken",
        type: "uint256",
      },
    ],
    name: "getRequiredIssuanceComponents",
    outputs: [
      {
        internalType: "address[]",
        name: "components",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "positions",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_issuanceModule",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_isDebtIssuance",
        type: "bool",
      },
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountSetToken",
        type: "uint256",
      },
    ],
    name: "getRequiredRedemptionComponents",
    outputs: [
      {
        internalType: "address[]",
        name: "components",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "positions",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountSetToken",
        type: "uint256",
      },
      {
        internalType: "bytes[]",
        name: "_componentQuotes",
        type: "bytes[]",
      },
      {
        internalType: "address",
        name: "_issuanceModule",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_isDebtIssuance",
        type: "bool",
      },
    ],
    name: "issueExactSetFromETH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "contract IERC20",
        name: "_inputToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountSetToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxAmountInputToken",
        type: "uint256",
      },
      {
        internalType: "bytes[]",
        name: "_componentQuotes",
        type: "bytes[]",
      },
      {
        internalType: "address",
        name: "_issuanceModule",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_isDebtIssuance",
        type: "bool",
      },
    ],
    name: "issueExactSetFromToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountSetToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minEthReceive",
        type: "uint256",
      },
      {
        internalType: "bytes[]",
        name: "_componentQuotes",
        type: "bytes[]",
      },
      {
        internalType: "address",
        name: "_issuanceModule",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_isDebtIssuance",
        type: "bool",
      },
    ],
    name: "redeemExactSetForETH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address",
      },
      {
        internalType: "contract IERC20",
        name: "_outputToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountSetToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minOutputReceive",
        type: "uint256",
      },
      {
        internalType: "bytes[]",
        name: "_componentQuotes",
        type: "bytes[]",
      },
      {
        internalType: "address",
        name: "_issuanceModule",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_isDebtIssuance",
        type: "bool",
      },
    ],
    name: "redeemExactSetForToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IExchangeIssuanceZeroEx__factory {
  static readonly abi = _abi;
  static createInterface(): IExchangeIssuanceZeroExInterface {
    return new utils.Interface(_abi) as IExchangeIssuanceZeroExInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExchangeIssuanceZeroEx {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IExchangeIssuanceZeroEx;
  }
}
