/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IDebtIssuanceModuleInterface extends utils.Interface {
  contractName: "IDebtIssuanceModule";
  functions: {
    "initialize(address,uint256,uint256,uint256,address,address)": FunctionFragment;
    "registerToIssuanceModule(address)": FunctionFragment;
    "unregisterFromIssuanceModule(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, BigNumberish, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerToIssuanceModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterFromIssuanceModule",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerToIssuanceModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterFromIssuanceModule",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IDebtIssuanceModule extends BaseContract {
  contractName: "IDebtIssuanceModule";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDebtIssuanceModuleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    initialize(
      _setToken: string,
      _maxManagerFee: BigNumberish,
      _managerIssueFee: BigNumberish,
      _managerRedeemFee: BigNumberish,
      _feeRecipient: string,
      _managerIssuanceHook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerToIssuanceModule(
      _setToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unregisterFromIssuanceModule(
      _setToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  initialize(
    _setToken: string,
    _maxManagerFee: BigNumberish,
    _managerIssueFee: BigNumberish,
    _managerRedeemFee: BigNumberish,
    _feeRecipient: string,
    _managerIssuanceHook: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerToIssuanceModule(
    _setToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unregisterFromIssuanceModule(
    _setToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    initialize(
      _setToken: string,
      _maxManagerFee: BigNumberish,
      _managerIssueFee: BigNumberish,
      _managerRedeemFee: BigNumberish,
      _feeRecipient: string,
      _managerIssuanceHook: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerToIssuanceModule(
      _setToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unregisterFromIssuanceModule(
      _setToken: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    initialize(
      _setToken: string,
      _maxManagerFee: BigNumberish,
      _managerIssueFee: BigNumberish,
      _managerRedeemFee: BigNumberish,
      _feeRecipient: string,
      _managerIssuanceHook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerToIssuanceModule(
      _setToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unregisterFromIssuanceModule(
      _setToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      _setToken: string,
      _maxManagerFee: BigNumberish,
      _managerIssueFee: BigNumberish,
      _managerRedeemFee: BigNumberish,
      _feeRecipient: string,
      _managerIssuanceHook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerToIssuanceModule(
      _setToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unregisterFromIssuanceModule(
      _setToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
